### PR TITLE
Add project configuaration.

### PR DESCRIPTION
**Pull request by jmattaa**
I've added the possibility to create a `lumen_config.json` file and configure the behavior of lumen. 

an example for a config json could be 
```js
{
    "model_provider": "ollama",
    "model": "mistral",
    // "api-key": "<api-key>", this could be added if needed
    "prefix": {
        "docs": "document changes",
        "feature": "new feature",
        // this accepts any key and will write this object as a string given to the AI prompt
    }
}
```

### CODE REVIEW

**Comment by jnsahaj** [comment]
Neat.

I have a couple of opinions

1.  I don't like the name `prefix` - doesn't communicate the idea well enough. I think a better name would be `commit_types`
2. Instead of `model_provider`, it should be `ai_provider` to stay consistent with the env var names
3. I prefer the name `LumenConfig` instead of `ProjectConfig`
4. The `configuration.rs` file should take care of all the 3 ways (file, cli-flags, env) we could get the config. So inside `run`, we should only see something like `let config = Config::build()`. It should also do all the error handling, by creating a new `LumenConfigError`.
5. Each of the command should now take a `config` of its own, so future additions to these commands will not affect the signature of the function. Instead of `fn draft(diff, context, commit_types)`, it should be `fn draft(diff, config)`. This also applies to other commands but we can change them later on.
6. The config should be extensible and applicable to all commands. `commit_types` is not applicable to `explain` or `list`, so the API should probably look something like `commands.draft.commit_types`
7. There should be a CLI flag to specify path of the config file, which defaults to `lumen.config.json`
8. I would like the default config to be named `lumen.config.json`, following the new eslint config's format

I do have some other points but these are the most important ones for now. 

Let me know if you have any concerns and if you would like to work on these changes. I am happy to pick up where you left off as well.

Note: I will not be having my laptop for this coming week 🌴 so expect responses to be delayed :)

**Comment by jnsahaj** [comment]
Heads up, I have made some changes in the direction of point 5. 
The change just refactors the command file and makes a step in the direction of command configs

Next: the `AIProvider` command implementations can just use the CommandType as an input instead of multiple arguments

**Comment by jnsahaj** [comment]
Update, point 5 is merged
Apologies for the conflicts, but the project structure is much more maintainable

**Comment by jmattaa** [comment]
I'll resolve the conflicts, and will start working on the listed points.

**Comment by jnsahaj** [comment]
Might be easier to start from scratch

**Comment by jmattaa** [comment]
Yeah, that sounds more reasonable. I've got one question, would you like the config to be a part of the `AIPrompt` struct, or should I pass it as it's own argument to the functions?

**Comment by jmattaa** [comment]
It wasn't that hard to merge, but check the code, I've implemented all the points except point 6. I'll be doing it and handling through `LumenError` in next commit

**Comment by jmattaa** [comment]
I've implemented point 6 in the latest commit now a json file would look like this:

```json
{
    "ai_model": "phind",
    "draft": {
        "docs": "Documentation only changes",
        "style": "Changes that do not affect the meaning of the code",
        "refactor": "A code change that neither fixes a bug nor adds a feature",
        "perf": "A code change that improves performance",
        "test": "Adding missing tests or correcting existing tests",
        "build": "Changes that affect the build system or external dependencies",
        "ci": "Changes to our CI configuration files and scripts",
        "chore": "Other changes that don't modify src or test files",
        "revert": "Reverts a previous commit",
        "feat": "A new feature",
        "fix": "A bug fix"
    }
}
```

**Comment by jmattaa** [comment]
I've resolved the conflicts with main and added error handling using the `LumenError`. Is there additional changes I should do?

**Comment by jnsahaj** [comment]
Hi, I don't have my laptop for a couple more days. I want to test this out before merging it and might also add some changes.

I'll prevent merging any other changes to not introduce new conflicts - thanks!

**Review by jnsahaj — APPROVED** [review]

**Comment by jnsahaj** [comment]
Merging your PR into `feature/project-config-file`
I would like to test it out and make some additional changes before merging to main

**Pull request merged**
