### PR TITLE
STDIN support for `explain` command implemented

### LINKED ISSUE #24: Add STDIN support for `explain` command
Basically, this should work
```sh
echo "HEAD" | lumen explain -
```

### PR DESCRIPTION
**Pull request by mulla028**
Closes #24 

## Description: 

Refactor Commit Handling and Improve `ExplainCommand`

### **Summary of Changes:**

This pull request introduces several improvements to the `ExplainCommand` functionality, including handling the `"-"` commit SHA in a more flexible and user-friendly way. The key changes are:

1. **Handling `"-"` Commit SHA by Reading from stdin:**
   - The commit SHA `"-"` is now treated as a signal to read the commit SHA from stdin, rather than trying to find a commit with the SHA `"-"`.
   - This feature enables more interactive usage, where users can pass the commit SHA via standard input. For example:
     ```bash
     echo "HEAD" | lumen explain -
     ```
   - When `"-"` is provided as the commit SHA, the program will read the commit SHA from stdin and process it.

2. **Refactor `ExplainCommand` to Handle Special Commit and Diff Cases:**
   - We refactored `ExplainCommand` to handle both `GitEntity::Commit` and `GitEntity::Diff` cases when `"-"` is encountered, allowing the program to read the commit SHA or diff from stdin accordingly.

3. **New `Commit::new_from_stdin` Method:**
   - Added a `new_from_stdin()` method to the `Commit` struct to read the commit SHA from stdin and create the `GitEntity::Commit` object dynamically. This method is used when the commit SHA is `"-"`.

### **Detailed Changes:**
- **`ExplainCommand` Updates:** The `ExplainCommand::new` function now handles `"-"` commit SHAs by reading from stdin. This enables the user to dynamically provide commit SHAs through standard input.
- **`Commit` Updates:** Introduced a new method `Commit::new_from_stdin()` to facilitate commit creation from stdin input, making the command more flexible for interactive use.
- **Refactored `main.rs` and `mod.rs`:** Changes in `main.rs` ensure that the commit SHA `"-"` is passed to the `Commit::new_from_stdin()` method, rather than being treated as an invalid commit. Additionally, `mod.rs` was updated to use the new `ExplainCommand::new()` method.

### **Why These Changes?**
- **Improved Flexibility:** By allowing stdin input for commit SHAs and diffs, the command becomes more interactive and user-friendly, making it easier for users to explore and explain commits dynamically.
- **Cleaner Code:** The refactor improves code structure, making it more maintainable by centralizing the logic for reading from stdin and handling special cases (`"-"`).

### CODE REVIEW

**Comment by jnsahaj** [comment]
A couple of comments
1. I don't think there is a need for stdin implementation for Diff. This can be safely removed
2. In my opinion, instead of adding a `Commit::new_from_stdin()`, it should be the job of `run` function in `main.rs` to substitute the `-` for the commit SHA. Rest should be handled as-is

So the only change there should be is in the `run` function in `main.rs`
I don't think there is a need for `ExplainCommand::new` to handle the `"-"`, since it is strongly typed

**Comment by jnsahaj** [comment]
Unrelated: It looks like the PR description was generated by an AI. If so, may I know what you are using for this?

**Comment by mulla028** [comment]
@jnsahaj yeah, for PR description I used the copilot 😁 If it's not acceptable in terms of you project, I can edit  description using my own words

**Comment by jnsahaj** [comment]
No that's totally fine - I was just curious :)

Let me know if you would like to incorporate the PR feedback in terms of the only change here being in the `run` function in `main.rs` at line 48.
Or I can make them on top of your PR

**Comment by mulla028** [comment]
@jnsahaj I would like to incorporate the PR's feedback

**Comment by mulla028** [comment]
Just want to make sure that I understand you clearly. You want to move the entire implementation to the main.rs?

**Comment by mulla028** [comment]
## Appreciation Comment

Very interesting and useful tool, thank you so much!

**Pull request merged**
